In [3]:
!pip install pymysql

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pymysql
  Downloading PyMySQL-1.0.2-py3-none-any.whl (43 kB)
     |████████████████████████████████| 43 kB 1.2 MB/s
Installing collected packages: pymysql
Successfully installed pymysql-1.0.2

In [1]:
import pandas as pd
import numpy as np
from collections import defaultdict
from scipy.stats import pearsonr
import pymysql

connection = pymysql.connect(
    user="j7e103",
    passwd="000000",
    host="j7e103.p.ssafy.io",
    port=3306,
    db="homidu",
    charset="utf8",
)
cursor = connection.cursor(pymysql.cursors.DictCursor)

In [8]:
sql = """select score from plantLike where user_id = 8"""
cursor.execute(sql)
list_user = cursor.fetchall()

In [10]:
SQL = 'SELECT * FROM plantLike'
df = pd.read_sql(SQL, connection)

In [27]:
df

      plant_id  user_id     age  score
0            2        2  40-60대      4
1            2        8  20-30대      3
2            2        9  20-30대      3
3            2       10  20-30대      4
4            2       11  20-30대      2
...        ...      ...     ...    ...
1645       203       68  40-60대      3
1646       203       69  20-30대      3
1647       203       70  20-30대      3
1648       203       71  20-30대      4
1649       203       72  40-60대      0

[1650 rows x 4 columns]

In [34]:
len(set(df['plant_id']))

25

In [40]:
set(df['plant_id'])

{2,
 6,
 14,
 42,
 50,
 62,
 68,
 71,
 75,
 84,
 93,
 95,
 103,
 111,
 112,
 120,
 122,
 130,
 160,
 174,
 176,
 177,
 179,
 200,
 203}

In [33]:
len(set(df['user_id']))

66

In [63]:
zeros = np.zeros((66, 25))
farm = pd.DataFrame(zeros, index=list(set(df['user_id'])), columns=sorted(list(set(df['plant_id']))))

In [64]:
farm

,2,6,14,42,50,62,68,71,75,84,...,120,122,130,160,174,176,177,179,200,203
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
69,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
70,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
71,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
72,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [59]:
farm[2].loc[2] = 3

In [47]:
sql = """select user_id, plant_id, score from plantLike"""
cursor.execute(sql)
list_user = cursor.fetchall()
list_user

[{'user_id': 2, 'plant_id': 2, 'score': 4},
 {'user_id': 8, 'plant_id': 2, 'score': 3},
 {'user_id': 9, 'plant_id': 2, 'score': 3},
 {'user_id': 10, 'plant_id': 2, 'score': 4},
 {'user_id': 11, 'plant_id': 2, 'score': 2},
 {'user_id': 12, 'plant_id': 2, 'score': 0},
 {'user_id': 13, 'plant_id': 2, 'score': 2},
 {'user_id': 14, 'plant_id': 2, 'score': 1},
 {'user_id': 15, 'plant_id': 2, 'score': 3},
 {'user_id': 16, 'plant_id': 2, 'score': 1},
 {'user_id': 17, 'plant_id': 2, 'score': 3},
 {'user_id': 18, 'plant_id': 2, 'score': 3},
 {'user_id': 19, 'plant_id': 2, 'score': 4},
 {'user_id': 20, 'plant_id': 2, 'score': 3},
 {'user_id': 21, 'plant_id': 2, 'score': 2},
 {'user_id': 22, 'plant_id': 2, 'score': 0},
 {'user_id': 23, 'plant_id': 2, 'score': 4},
 {'user_id': 24, 'plant_id': 2, 'score': 3},
 {'user_id': 25, 'plant_id': 2, 'score': 1},
 {'user_id': 26, 'plant_id': 2, 'score': 4},
 {'user_id': 27, 'plant_id': 2, 'score': 2},
 {'user_id': 28, 'plant_id': 2, 'score': 4},
 {'user_id': 29, 'plant_id': 2, 'score': 1},
 {'user_id': 30, 'plant_id': 2, 'score': 2},
 {'user_id': 31, 'plant_id': 2, 'score': 3},
 {'user_id': 32, 'plant_id': 2, 'score': 3},
 {'user_id': 33, 'plant_id': 2, 'score': 3},
 {'user_id': 34, 'plant_id': 2, 'score': 1},
 {'user_id': 35, 'plant_id': 2, 'score': 1},
 {'user_id': 36, 'plant_id': 2, 'score': 2},
 {'user_id': 37, 'plant_id': 2, 'score': 2},
 {'user_id': 38, 'plant_id': 2, 'score': 3},
 {'user_id': 39, 'plant_id': 2, 'score': 2},
 {'user_id': 40, 'plant_id': 2, 'score': 1},
 {'user_id': 41, 'plant_id': 2, 'score': 3},
 {'user_id': 42, 'plant_id': 2, 'score': 4},
 {'user_id': 43, 'plant_id': 2, 'score': 0},
 {'user_id': 44, 'plant_id': 2, 'score': 4},
 {'user_id': 45, 'plant_id': 2, 'score': 4},
 {'user_id': 46, 'plant_id': 2, 'score': 0},
 {'user_id': 47, 'plant_id': 2, 'score': 4},
 {'user_id': 48, 'plant_id': 2, 'score': 1},
 {'user_id': 49, 'plant_id': 2, 'score': 3},
 {'user_id': 50, 'plant_id': 2, 'score': 1},
 {'user_id': 51, 'plant_id': 2, 'score': 2},
 {'user_id': 52, 'plant_id': 2, 'score': 4},
 {'user_id': 53, 'plant_id': 2, 'score': 1},
 {'user_id': 54, 'plant_id': 2, 'score': 3},
 {'user_id': 55, 'plant_id': 2, 'score': 3},
 {'user_id': 56, 'plant_id': 2, 'score': 0},
 {'user_id': 57, 'plant_id': 2, 'score': 4},
 {'user_id': 58, 'plant_id': 2, 'score': 2},
 {'user_id': 59, 'plant_id': 2, 'score': 4},
 {'user_id': 60, 'plant_id': 2, 'score': 0},
 {'user_id': 61, 'plant_id': 2, 'score': 3},
 {'user_id': 62, 'plant_id': 2, 'score': 3},
 {'user_id': 63, 'plant_id': 2, 'score': 4},
 {'user_id': 64, 'plant_id': 2, 'score': 3},
 {'user_id': 65, 'plant_id': 2, 'score': 4},
 {'user_id': 66, 'plant_id': 2, 'score': 2},
 {'user_id': 67, 'plant_id': 2, 'score': 3},
 {'user_id': 68, 'plant_id': 2, 'score': 4},
 {'user_id': 69, 'plant_id': 2, 'score': 0},
 {'user_id': 70, 'plant_id': 2, 'score': 3},
 {'user_id': 71, 'plant_id': 2, 'score': 4},
 {'user_id': 72, 'plant_id': 2, 'score': 0},
 {'user_id': 2, 'plant_id': 6, 'score': 1},
 {'user_id': 8, 'plant_id': 6, 'score': 2},
 {'user_id': 9, 'plant_id': 6, 'score': 0},
 {'user_id': 10, 'plant_id': 6, 'score': 1},
 {'user_id': 11, 'plant_id': 6, 'score': 4},
 {'user_id': 12, 'plant_id': 6, 'score': 3},
 {'user_id': 13, 'plant_id': 6, 'score': 4},
 {'user_id': 14, 'plant_id': 6, 'score': 2},
 {'user_id': 15, 'plant_id': 6, 'score': 4},
 {'user_id': 16, 'plant_id': 6, 'score': 2},
 {'user_id': 17, 'plant_id': 6, 'score': 4},
 {'user_id': 18, 'plant_id': 6, 'score': 2},
 {'user_id': 19, 'plant_id': 6, 'score': 4},
 {'user_id': 20, 'plant_id': 6, 'score': 3},
 {'user_id': 21, 'plant_id': 6, 'score': 3},
 {'user_id': 22, 'plant_id': 6, 'score': 2},
 {'user_id': 23, 'plant_id': 6, 'score': 2},
 {'user_id': 24, 'plant_id': 6, 'score': 2},
 {'user_id': 25, 'plant_id': 6, 'score': 1},
 {'user_id': 26, 'plant_id': 6, 'score': 4},
 {'user_id': 27, 'plant_id': 6, 'score': 0},
 {'user_id': 28, 'plant_id': 6, 'score': 3},
 {'user_id': 29, 'plant_id': 6, 'score': 1},
 {'user_id': 30, 'plant_id': 6, 'score': 0},
 {'user_id': 31, 'plant_id': 6, 'score': 2},
 {'user_id': 32, 'plant_id': 6, 'score': 3},
 {'user_id': 33, 'plant_id': 6, 'score': 1},
 {'user_id': 34, 'plant_id': 6, 'score': 1},
 {'user_id': 35, 'plant_id': 6, 'score': 1},
 {'user_id': 36, 'plant_id': 6, 'score': 3},
 {'user_id': 37, 'plant_id': 6, 'score': 1},
 {'user_id': 38, 'plant_id': 6, 'score': 4},
 {'user_id': 39, 'plant_id': 6, 'score': 2},
 {'user_id': 40, 'plant_id': 6, 'score': 1},
 {'user_id': 41, 'plant_id': 6, 'score': 1},
 {'user_id': 42, 'plant_id': 6, 'score': 4},
 {'user_id': 43, 'plant_id': 6, 'score': 3},
 {'user_id': 44, 'plant_id': 6, 'score': 4},
 {'user_id': 45, 'plant_id': 6, 'score': 4},
 {'user_id': 46, 'plant_id': 6, 'score': 3},
 {'user_id': 47, 'plant_id': 6, 'score': 2},
 {'user_id': 48, 'plant_id': 6, 'score': 3},
 {'user_id': 49, 'plant_id': 6, 'score': 2},
 {'user_id': 50, 'plant_id': 6, 'score': 1},
 {'user_id': 51, 'plant_id': 6, 'score': 3},
 {'user_id': 52, 'plant_id': 6, 'score': 0},
 {'user_id': 53, 'plant_id': 6, 'score': 2},
 {'user_id': 54, 'plant_id': 6, 'score': 1},
 {'user_id': 55, 'plant_id': 6, 'score': 1},
 {'user_id': 56, 'plant_id': 6, 'score': 1},
 {'user_id': 57, 'plant_id': 6, 'score': 2},
 {'user_id': 58, 'plant_id': 6, 'score': 1},
 {'user_id': 59, 'plant_id': 6, 'score': 2},
 {'user_id': 60, 'plant_id': 6, 'score': 0},
 {'user_id': 61, 'plant_id': 6, 'score': 1},
 {'user_id': 62, 'plant_id': 6, 'score': 3},
 {'user_id': 63, 'plant_id': 6, 'score': 2},
 {'user_id': 64, 'plant_id': 6, 'score': 1},
 {'user_id': 65, 'plant_id': 6, 'score': 3},
 {'user_id': 66, 'plant_id': 6, 'score': 4},
 {'user_id': 67, 'plant_id': 6, 'score': 4},
 {'user_id': 68, 'plant_id': 6, 'score': 4},
 {'user_id': 69, 'plant_id': 6, 'score': 0},
 {'user_id': 70, 'plant_id': 6, 'score': 3},
 {'user_id': 71, 'plant_id': 6, 'score': 4},
 {'user_id': 72, 'plant_id': 6, 'score': 0},
 {'user_id': 2, 'plant_id': 14, 'score': 3},
 {'user_id': 8, 'plant_id': 14, 'score': 3},
 {'user_id': 9, 'plant_id': 14, 'score': 3},
 {'user_id': 10, 'plant_id': 14, 'score': 0},
 {'user_id': 11, 'plant_id': 14, 'score': 3},
 {'user_id': 12, 'plant_id': 14, 'score': 1},
 {'user_id': 13, 'plant_id': 14, 'score': 1},
 {'user_id': 14, 'plant_id': 14, 'score': 1},
 {'user_id': 15, 'plant_id': 14, 'score': 3},
 {'user_id': 16, 'plant_id': 14, 'score': 2},
 {'user_id': 17, 'plant_id': 14, 'score': 4},
 {'user_id': 18, 'plant_id': 14, 'score': 3},
 {'user_id': 19, 'plant_id': 14, 'score': 0},
 {'user_id': 20, 'plant_id': 14, 'score': 3},
 {'user_id': 21, 'plant_id': 14, 'score': 4},
 {'user_id': 22, 'plant_id': 14, 'score': 0},
 {'user_id': 23, 'plant_id': 14, 'score': 3},
 {'user_id': 24, 'plant_id': 14, 'score': 2},
 {'user_id': 25, 'plant_id': 14, 'score': 0},
 {'user_id': 26, 'plant_id': 14, 'score': 4},
 {'user_id': 27, 'plant_id': 14, 'score': 1},
 {'user_id': 28, 'plant_id': 14, 'score': 1},
 {'user_id': 29, 'plant_id': 14, 'score': 1},
 {'user_id': 30, 'plant_id': 14, 'score': 1},
 {'user_id': 31, 'plant_id': 14, 'score': 3},
 {'user_id': 32, 'plant_id': 14, 'score': 3},
 {'user_id': 33, 'plant_id': 14, 'score': 2},
 {'user_id': 34, 'plant_id': 14, 'score': 2},
 {'user_id': 35, 'plant_id': 14, 'score': 2},
 {'user_id': 36, 'plant_id': 14, 'score': 2},
 {'user_id': 37, 'plant_id': 14, 'score': 1},
 {'user_id': 38, 'plant_id': 14, 'score': 1},
 {'user_id': 39, 'plant_id': 14, 'score': 2},
 {'user_id': 40, 'plant_id': 14, 'score': 1},
 {'user_id': 41, 'plant_id': 14, 'score': 1},
 {'user_id': 42, 'plant_id': 14, 'score': 3},
 {'user_id': 43, 'plant_id': 14, 'score': 1},
 {'user_id': 44, 'plant_id': 14, 'score': 3},
 {'user_id': 45, 'plant_id': 14, 'score': 2},
 {'user_id': 46, 'plant_id': 14, 'score': 0},
 {'user_id': 47, 'plant_id': 14, 'score': 2},
 {'user_id': 48, 'plant_id': 14, 'score': 2},
 {'user_id': 49, 'plant_id': 14, 'score': 3},
 {'user_id': 50, 'plant_id': 14, 'score': 1},
 {'user_id': 51, 'plant_id': 14, 'score': 2},
 {'user_id': 52, 'plant_id': 14, 'score': 0},
 {'user_id': 53, 'plant_id': 14, 'score': 3},
 {'user_id': 54, 'plant_id': 14, 'score': 1},
 {'user_id': 55, 'plant_id': 14, 'score': 3},
 {'user_id': 56, 'plant_id': 14, 'score': 3},
 {'user_id': 57, 'plant_id': 14, 'score': 2},
 {'user_id': 58, 'plant_id': 14, 'score': 3},
 {'user_id': 59, 'plant_id': 14, 'score': 4},
 {'user_id': 60, 'plant_id': 14, 'score': 4},
 {'user_id': 61, 'plant_id': 14, 'score': 1},
 {'user_id': 62, 'plant_id': 14, 'score': 1},
 {'user_id': 63, 'plant_id': 14, 'score': 1},
 {'user_id': 64, 'plant_id': 14, 'score': 0},
 {'user_id': 65, 'plant_id': 14, 'score': 3},
 {'user_id': 66, 'plant_id': 14, 'score': 3},
 {'user_id': 67, 'plant_id': 14, 'score': 2},
 {'user_id': 68, 'plant_id': 14, 'score': 3},
 {'user_id': 69, 'plant_id': 14, 'score': 4},
 {'user_id': 70, 'plant_id': 14, 'score': 3},
 {'user_id': 71, 'plant_id': 14, 'score': 4},
 {'user_id': 72, 'plant_id': 14, 'score': 0},
 {'user_id': 2, 'plant_id': 42, 'score': 3},
 {'user_id': 8, 'plant_id': 42, 'score': 1},
 {'user_id': 9, 'plant_id': 42, 'score': 3},
 {'user_id': 10, 'plant_id': 42, 'score': 0},
 {'user_id': 11, 'plant_id': 42, 'score': 1},
 {'user_id': 12, 'plant_id': 42, 'score': 4},
 {'user_id': 13, 'plant_id': 42, 'score': 1},
 {'user_id': 14, 'plant_id': 42, 'score': 0},
 {'user_id': 15, 'plant_id': 42, 'score': 2},
 {'user_id': 16, 'plant_id': 42, 'score': 2},
 {'user_id': 17, 'plant_id': 42, 'score': 3},
 {'user_id': 18, 'plant_id': 42, 'score': 2},
 {'user_id': 19, 'plant_id': 42, 'score': 0},
 {'user_id': 20, 'plant_id': 42, 'score': 3},
 {'user_id': 21, 'plant_id': 42, 'score': 3},
 {'user_id': 22, 'plant_id': 42, 'score': 3},
 {'user_id': 23, 'plant_id': 42, 'score': 3},
 {'user_id': 24, 'plant_id': 42, 'score': 3},
 {'user_id': 25, 'plant_id': 42, 'score': 0},
 {'user_id': 26, 'plant_id': 42, 'score': 2},
 {'user_id': 27, 'plant_id': 42, 'score': 2},
 {'user_id': 28, 'plant_id': 42, 'score': 1},
 {'user_id': 29, 'plant_id': 42, 'score': 3},
 {'user_id': 30, 'plant_id': 42, 'score': 1},
 {'user_id': 31, 'plant_id': 42, 'score': 2},
 {'user_id': 32, 'plant_id': 42, 'score': 3},
 {'user_id': 33, 'plant_id': 42, 'score': 2},
 {'user_id': 34, 'plant_id': 42, 'score': 1},
 {'user_id': 35, 'plant_id': 42, 'score': 2},
 {'user_id': 36, 'plant_id': 42, 'score': 3},
 {'user_id': 37, 'plant_id': 42, 'score': 2},
 {'user_id': 38, 'plant_id': 42, 'score': 3},
 {'user_id': 39, 'plant_id': 42, 'score': 2},
 {'user_id': 40, 'plant_id': 42, 'score': 2},
 {'user_id': 41, 'plant_id': 42, 'score': 1},
 {'user_id': 42, 'plant_id': 42, 'score': 4},
 {'user_id': 43, 'plant_id': 42, 'score': 3},
 {'user_id': 44, 'plant_id': 42, 'score': 3},
 {'user_id': 45, 'plant_id': 42, 'score': 2},
 {'user_id': 46, 'plant_id': 42, 'score': 3},
 {'user_id': 47, 'plant_id': 42, 'score': 1},
 {'user_id': 48, 'plant_id': 42, 'score': 4},
 {'user_id': 49, 'plant_id': 42, 'score': 2},
 {'user_id': 50, 'plant_id': 42, 'score': 1},
 {'user_id': 51, 'plant_id': 42, 'score': 3},
 {'user_id': 52, 'plant_id': 42, 'score': 0},
 {'user_id': 53, 'plant_id': 42, 'score': 0},
 {'user_id': 54, 'plant_id': 42, 'score': 2},
 {'user_id': 55, 'plant_id': 42, 'score': 3},
 {'user_id': 56, 'plant_id': 42, 'score': 1},
 {'user_id': 57, 'plant_id': 42, 'score': 3},
 {'user_id': 58, 'plant_id': 42, 'score': 2},
 {'user_id': 59, 'plant_id': 42, 'score': 4},
 {'user_id': 60, 'plant_id': 42, 'score': 3},
 {'user_id': 61, 'plant_id': 42, 'score': 3},
 {'user_id': 62, 'plant_id': 42, 'score': 1},
 {'user_id': 63, 'plant_id': 42, 'score': 0},
 {'user_id': 64, 'plant_id': 42, 'score': 0},
 {'user_id': 65, 'plant_id': 42, 'score': 4},
 {'user_id': 66, 'plant_id': 42, 'score': 2},
 {'user_id': 67, 'plant_id': 42, 'score': 0},
 {'user_id': 68, 'plant_id': 42, 'score': 4},
 {'user_id': 69, 'plant_id': 42, 'score': 0},
 {'user_id': 70, 'plant_id': 42, 'score': 3},
 {'user_id': 71, 'plant_id': 42, 'score': 4},
 {'user_id': 72, 'plant_id': 42, 'score': 0},
 {'user_id': 2, 'plant_id': 50, 'score': 2},
 {'user_id': 8, 'plant_id': 50, 'score': 1},
 {'user_id': 9, 'plant_id': 50, 'score': 3},
 {'user_id': 10, 'plant_id': 50, 'score': 2},
 {'user_id': 11, 'plant_id': 50, 'score': 4},
 {'user_id': 12, 'plant_id': 50, 'score': 2},
 {'user_id': 13, 'plant_id': 50, 'score': 4},
 {'user_id': 14, 'plant_id': 50, 'score': 4},
 {'user_id': 15, 'plant_id': 50, 'score': 3},
 {'user_id': 16, 'plant_id': 50, 'score': 1},
 {'user_id': 17, 'plant_id': 50, 'score': 4},
 {'user_id': 18, 'plant_id': 50, 'score': 3},
 {'user_id': 19, 'plant_id': 50, 'score': 0},
 {'user_id': 20, 'plant_id': 50, 'score': 3},
 {'user_id': 21, 'plant_id': 50, 'score': 4},
 {'user_id': 22, 'plant_id': 50, 'score': 4},
 {'user_id': 23, 'plant_id': 50, 'score': 4},
 {'user_id': 24, 'plant_id': 50, 'score': 3},
 {'user_id': 25, 'plant_id': 50, 'score': 2},
 {'user_id': 26, 'plant_id': 50, 'score': 2},
 {'user_id': 27, 'plant_id': 50, 'score': 1},
 {'user_id': 28, 'plant_id': 50, 'score': 1},
 {'user_id': 29, 'plant_id': 50, 'score': 4},
 {'user_id': 30, 'plant_id': 50, 'score': 3},
 {'user_id': 31, 'plant_id': 50, 'score': 3},
 {'user_id': 32, 'plant_id': 50, 'score': 3},
 {'user_id': 33, 'plant_id': 50, 'score': 3},
 {'user_id': 34, 'plant_id': 50, 'score': 3},
 {'user_id': 35, 'plant_id': 50, 'score': 4},
 {'user_id': 36, 'plant_id': 50, 'score': 3},
 {'user_id': 37, 'plant_id': 50, 'score': 2},
 {'user_id': 38, 'plant_id': 50, 'score': 3},
 {'user_id': 39, 'plant_id': 50, 'score': 2},
 {'user_id': 40, 'plant_id': 50, 'score': 3},
 {'user_id': 41, 'plant_id': 50, 'score': 3},
 {'user_id': 42, 'plant_id': 50, 'score': 4},
 {'user_id': 43, 'plant_id': 50, 'score': 2},
 {'user_id': 44, 'plant_id': 50, 'score': 2},
 {'user_id': 45, 'plant_id': 50, 'score': 2},
 {'user_id': 46, 'plant_id': 50, 'score': 3},
 {'user_id': 47, 'plant_id': 50, 'score': 3},
 {'user_id': 48, 'plant_id': 50, 'score': 4},
 {'user_id': 49, 'plant_id': 50, 'score': 3},
 {'user_id': 50, 'plant_id': 50, 'score': 2},
 {'user_id': 51, 'plant_id': 50, 'score': 3},
 {'user_id': 52, 'plant_id': 50, 'score': 2},
 {'user_id': 53, 'plant_id': 50, 'score': 3},
 {'user_id': 54, 'plant_id': 50, 'score': 3},
 {'user_id': 55, 'plant_id': 50, 'score': 3},
 {'user_id': 56, 'plant_id': 50, 'score': 3},
 {'user_id': 57, 'plant_id': 50, 'score': 3},
 {'user_id': 58, 'plant_id': 50, 'score': 3},
 {'user_id': 59, 'plant_id': 50, 'score': 4},
 {'user_id': 60, 'plant_id': 50, 'score': 3},
 {'user_id': 61, 'plant_id': 50, 'score': 4},
 {'user_id': 62, 'plant_id': 50, 'score': 1},
 {'user_id': 63, 'plant_id': 50, 'score': 0},
 {'user_id': 64, 'plant_id': 50, 'score': 3},
 {'user_id': 65, 'plant_id': 50, 'score': 4},
 {'user_id': 66, 'plant_id': 50, 'score': 3},
 {'user_id': 67, 'plant_id': 50, 'score': 4},
 {'user_id': 68, 'plant_id': 50, 'score': 2},
 {'user_id': 69, 'plant_id': 50, 'score': 4},
 {'user_id': 70, 'plant_id': 50, 'score': 3},
 {'user_id': 71, 'plant_id': 50, 'score': 3},
 {'user_id': 72, 'plant_id': 50, 'score': 0},
 {'user_id': 2, 'plant_id': 62, 'score': 0},
 {'user_id': 8, 'plant_id': 62, 'score': 1},
 {'user_id': 9, 'plant_id': 62, 'score': 1},
 {'user_id': 10, 'plant_id': 62, 'score': 2},
 {'user_id': 11, 'plant_id': 62, 'score': 4},
 {'user_id': 12, 'plant_id': 62, 'score': 3},
 {'user_id': 13, 'plant_id': 62, 'score': 3},
 {'user_id': 14, 'plant_id': 62, 'score': 2},
 {'user_id': 15, 'plant_id': 62, 'score': 2},
 {'user_id': 16, 'plant_id': 62, 'score': 2},
 {'user_id': 17, 'plant_id': 62, 'score': 4},
 {'user_id': 18, 'plant_id': 62, 'score': 3},
 {'user_id': 19, 'plant_id': 62, 'score': 0},
 {'user_id': 20, 'plant_id': 62, 'score': 1},
 {'user_id': 21, 'plant_id': 62, 'score': 2},
 {'user_id': 22, 'plant_id': 62, 'score': 4},
 {'user_id': 23, 'plant_id': 62, 'score': 4},
 {'user_id': 24, 'plant_id': 62, 'score': 2},
 {'user_id': 25, 'plant_id': 62, 'score': 3},
 {'user_id': 26, 'plant_id': 62, 'score': 2},
 {'user_id': 27, 'plant_id': 62, 'score': 0},
 {'user_id': 28, 'plant_id': 62, 'score': 2},
 {'user_id': 29, 'plant_id': 62, 'score': 1},
 {'user_id': 30, 'plant_id': 62, 'score': 1},
 {'user_id': 31, 'plant_id': 62, 'score': 3},
 {'user_id': 32, 'plant_id': 62, 'score': 3},
 {'user_id': 33, 'plant_id': 62, 'score': 0},
 {'user_id': 34, 'plant_id': 62, 'score': 2},
 {'user_id': 35, 'plant_id': 62, 'score': 2},
 {'user_id': 36, 'plant_id': 62, 'score': 3},
 {'user_id': 37, 'plant_id': 62, 'score': 1},
 {'user_id': 38, 'plant_id': 62, 'score': 3},
 {'user_id': 39, 'plant_id': 62, 'score': 2},
 {'user_id': 40, 'plant_id': 62, 'score': 4},
 {'user_id': 41, 'plant_id': 62, 'score': 3},
 {'user_id': 42, 'plant_id': 62, 'score': 4},
 {'user_id': 43, 'plant_id': 62, 'score': 4},
 {'user_id': 44, 'plant_id': 62, 'score': 4},
 {'user_id': 45, 'plant_id': 62, 'score': 2},
 {'user_id': 46, 'plant_id': 62, 'score': 0},
 {'user_id': 47, 'plant_id': 62, 'score': 4},
 {'user_id': 48, 'plant_id': 62, 'score': 4},
 {'user_id': 49, 'plant_id': 62, 'score': 3},
 {'user_id': 50, 'plant_id': 62, 'score': 3},
 {'user_id': 51, 'plant_id': 62, 'score': 3},
 {'user_id': 52, 'plant_id': 62, 'score': 0},
 {'user_id': 53, 'plant_id': 62, 'score': 3},
 {'user_id': 54, 'plant_id': 62, 'score': 1},
 {'user_id': 55, 'plant_id': 62, 'score': 4},
 {'user_id': 56, 'plant_id': 62, 'score': 3},
 {'user_id': 57, 'plant_id': 62, 'score': 3},
 {'user_id': 58, 'plant_id': 62, 'score': 2},
 {'user_id': 59, 'plant_id': 62, 'score': 4},
 {'user_id': 60, 'plant_id': 62, 'score': 0},
 {'user_id': 61, 'plant_id': 62, 'score': 2},
 {'user_id': 62, 'plant_id': 62, 'score': 1},
 {'user_id': 63, 'plant_id': 62, 'score': 1},
 {'user_id': 64, 'plant_id': 62, 'score': 1},
 {'user_id': 65, 'plant_id': 62, 'score': 2},
 {'user_id': 66, 'plant_id': 62, 'score': 3},
 {'user_id': 67, 'plant_id': 62, 'score': 3},
 {'user_id': 68, 'plant_id': 62, 'score': 2},
 {'user_id': 69, 'plant_id': 62, 'score': 4},
 {'user_id': 70, 'plant_id': 62, 'score': 2},
 {'user_id': 71, 'plant_id': 62, 'score': 2},
 {'user_id': 72, 'plant_id': 62, 'score': 0},
 {'user_id': 2, 'plant_id': 68, 'score': 1},
 {'user_id': 8, 'plant_id': 68, 'score': 2},
 {'user_id': 9, 'plant_id': 68, 'score': 3},
 {'user_id': 10, 'plant_id': 68, 'score': 0},
 {'user_id': 11, 'plant_id': 68, 'score': 1},
 {'user_id': 12, 'plant_id': 68, 'score': 4},
 {'user_id': 13, 'plant_id': 68, 'score': 2},
 {'user_id': 14, 'plant_id': 68, 'score': 3},
 {'user_id': 15, 'plant_id': 68, 'score': 2},
 {'user_id': 16, 'plant_id': 68, 'score': 3},
 {'user_id': 17, 'plant_id': 68, 'score': 3},
 {'user_id': 18, 'plant_id': 68, 'score': 3},
 {'user_id': 19, 'plant_id': 68, 'score': 0},
 {'user_id': 20, 'plant_id': 68, 'score': 3},
 {'user_id': 21, 'plant_id': 68, 'score': 4},
 {'user_id': 22, 'plant_id': 68, 'score': 4},
 {'user_id': 23, 'plant_id': 68, 'score': 3},
 {'user_id': 24, 'plant_id': 68, 'score': 1},
 {'user_id': 25, 'plant_id': 68, 'score': 0},
 {'user_id': 26, 'plant_id': 68, 'score': 2},
 {'user_id': 27, 'plant_id': 68, 'score': 0},
 {'user_id': 28, 'plant_id': 68, 'score': 2},
 {'user_id': 29, 'plant_id': 68, 'score': 1},
 {'user_id': 30, 'plant_id': 68, 'score': 3},
 {'user_id': 31, 'plant_id': 68, 'score': 3},
 {'user_id': 32, 'plant_id': 68, 'score': 4},
 {'user_id': 33, 'plant_id': 68, 'score': 4},
 {'user_id': 34, 'plant_id': 68, 'score': 3},
 {'user_id': 35, 'plant_id': 68, 'score': 2},
 {'user_id': 36, 'plant_id': 68, 'score': 3},
 {'user_id': 37, 'plant_id': 68, 'score': 2},
 {'user_id': 38, 'plant_id': 68, 'score': 3},
 {'user_id': 39, 'plant_id': 68, 'score': 4},
 {'user_id': 40, 'plant_id': 68, 'score': 0},
 {'user_id': 41, 'plant_id': 68, 'score': 3},
 {'user_id': 42, 'plant_id': 68, 'score': 3},
 {'user_id': 43, 'plant_id': 68, 'score': 0},
 {'user_id': 44, 'plant_id': 68, 'score': 4},
 {'user_id': 45, 'plant_id': 68, 'score': 2},
 {'user_id': 46, 'plant_id': 68, 'score': 3},
 {'user_id': 47, 'plant_id': 68, 'score': 2},
 {'user_id': 48, 'plant_id': 68, 'score': 3},

In [65]:
for user in list_user:
    farm[user['plant_id']].loc[user['user_id']] = user['score']

In [67]:
farm

,2,6,14,42,50,62,68,71,75,84,...,120,122,130,160,174,176,177,179,200,203
2,4.0,1.0,3.0,3.0,2.0,0.0,1.0,2.0,4.0,3.0,...,4.0,3.0,3.0,4.0,4.0,3.0,4.0,3.0,1.0,4.0
8,3.0,2.0,3.0,1.0,1.0,1.0,2.0,1.0,4.0,1.0,...,4.0,2.0,3.0,0.0,2.0,0.0,2.0,2.0,2.0,3.0
9,3.0,0.0,3.0,3.0,3.0,1.0,3.0,0.0,0.0,4.0,...,4.0,1.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,2.0
10,4.0,1.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,2.0,...,2.0,3.0,4.0,0.0,3.0,4.0,0.0,3.0,0.0,4.0
11,2.0,4.0,3.0,1.0,4.0,4.0,1.0,4.0,0.0,4.0,...,1.0,3.0,2.0,0.0,3.0,2.0,2.0,4.0,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,4.0,4.0,3.0,4.0,2.0,2.0,0.0,3.0,3.0,1.0,...,1.0,1.0,1.0,1.0,0.0,3.0,1.0,4.0,1.0,3.0
69,0.0,0.0,4.0,0.0,4.0,4.0,2.0,0.0,0.0,2.0,...,2.0,0.0,4.0,3.0,0.0,0.0,4.0,3.0,0.0,3.0
70,3.0,3.0,3.0,3.0,3.0,2.0,1.0,3.0,2.0,3.0,...,2.0,3.0,2.0,1.0,3.0,2.0,3.0,1.0,2.0,3.0
71,4.0,4.0,4.0,4.0,3.0,2.0,3.0,1.0,3.0,1.0,...,3.0,4.0,2.0,2.0,1.0,2.0,3.0,4.0,1.0,4.0
72,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [69]:
# 유사도 테이블 생성
n = len(farm.index)
zeros = np.zeros((n, n))
sim = pd.DataFrame(zeros, index=list(farm.index), columns=list(farm.index))
sim

,2,8,9,10,11,12,13,14,15,16,...,63,64,65,66,67,68,69,70,71,72
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
69,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
70,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
71,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
72,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [70]:
# 유사도 계산
for name1 in sim.index:
    for name2 in sim.index:
        sim[name1].loc[name2] = round(pearsonr(list(farm.loc[name1]), list(farm.loc[name2]))[0], 4) # scipy 라이브러리 사용
sim

/usr/local/lib/python3.7/dist-packages/scipy/stats/stats.py:4023: PearsonRConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(PearsonRConstantInputWarning())

,2,8,9,10,11,12,13,14,15,16,...,63,64,65,66,67,68,69,70,71,72
2,1.0000,0.2889,0.1484,0.1796,-0.3330,-0.2406,0.1111,-0.3548,-0.1622,-0.2552,...,-0.0412,0.1531,-0.1271,0.0289,-0.3013,-0.0577,0.0908,0.0336,0.1405,NaN
8,0.2889,1.0000,0.1249,0.0692,-0.2698,-0.0610,0.0594,-0.0905,0.1645,0.1017,...,0.1570,0.5272,-0.1131,0.0297,-0.0407,0.0676,-0.0314,-0.2418,0.3508,NaN
9,0.1484,0.1249,1.0000,0.1100,0.0470,0.3721,-0.0349,0.3713,0.3136,0.0078,...,0.1840,0.1720,0.4000,-0.1448,-0.0601,-0.1600,0.0619,0.2197,0.0176,NaN
10,0.1796,0.0692,0.1100,1.0000,0.4374,0.1728,0.0756,0.3162,0.5071,0.2200,...,0.2926,0.2933,0.1079,-0.0970,0.4089,-0.0453,0.0415,0.2290,-0.0046,NaN
11,-0.3330,-0.2698,0.0470,0.4374,1.0000,0.1642,0.2590,0.3435,0.5307,-0.0765,...,0.3202,0.1020,0.4445,0.0193,0.6635,0.1364,0.1635,0.5602,-0.0181,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,-0.0577,0.0676,-0.1600,-0.0453,0.1364,-0.4284,-0.3202,-0.2251,0.1679,-0.2229,...,0.3221,0.3043,0.3572,-0.4568,0.0699,1.0000,-0.3243,0.0197,0.5762,NaN
69,0.0908,-0.0314,0.0619,0.0415,0.1635,-0.0254,0.3296,0.0937,0.0399,0.0472,...,-0.2511,-0.0573,-0.1228,0.4316,-0.1257,-0.3243,1.0000,-0.1141,0.0219,NaN
70,0.0336,-0.2418,0.2197,0.2290,0.5602,0.1873,-0.0722,0.1164,0.1918,-0.2877,...,0.1896,-0.2329,0.4700,-0.1864,0.2594,0.0197,-0.1141,1.0000,-0.0394,NaN
71,0.1405,0.3508,0.0176,-0.0046,-0.0181,-0.1131,0.0084,0.0712,0.3396,-0.0313,...,0.4436,0.3286,0.4122,0.0966,-0.0332,0.5762,0.0219,-0.0394,1.0000,NaN
72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [80]:
def get_recommendation(name):
    plants =list(farm.columns)
    score_dic=defaultdict(int) # 평점
    sim_dic=defaultdict(int) # 유사도

    for name2, sim_score in dict(sim[name]).items():
        if sim_score > 0 and name != name2: # 박현정과 유사도가 0 이상인 사람에 대해서
            for plant in plants: # 모든 식물을 조사해본다.
                score = 0
                if not farm.loc[name][plant]: # 만약 박현정이 그 식물을 키우지 않는다면,
                    score += farm.loc[name2][plant] * sim_score # 평점 예측 
                    score_dic[plant] += score
                    sim_dic[plant] += sim_score
    
    #print(score_dic)
    #print(sim_dic)
    ret = []
    for key in score_dic.keys():
        score_dic[key] = score_dic[key]/sim_dic[key]
        ret.append([score_dic[key], key])
    
    return sorted(ret, key = lambda x:x[0], reverse = True)

get_recommendation(2)

[[1.3665617623918174, 62]]

In [81]:
get_recommendation(8)

[[2.049064046226774, 93], [1.5177675512958029, 176], [1.0986471056364833, 160]]

In [82]:
get_recommendation(9)

[[2.227504719848965, 112],
 [1.9094748968033026, 103],
 [1.8338133179738256, 6],
 [1.592781031007008, 93],
 [1.4648251255959812, 95],
 [1.4587693193817801, 179],
 [1.3679642251447957, 75],
 [1.3535246872100097, 177],
 [1.247272087293207, 200],
 [1.1721064925922373, 71],
 [1.1700825573581646, 130],
 [1.1566429874244029, 176],
 [0.8964113148379256, 160]]

In [83]:
get_recommendation(10)

[[2.2485667676532275, 68],
 [1.881566068515498, 14],
 [1.8121277091587047, 93],
 [1.788655325099045, 42],
 [1.5354835702633418, 95],
 [1.5178932649732, 75],
 [1.472598461896994, 177],
 [1.4106455371708226, 111],
 [1.3254998834770448, 71],
 [1.1927382894430203, 200],
 [0.8494616639477977, 160]]

In [84]:
get_recommendation(11)

[[1.2341434999535676, 75], [0.8838357829687722, 160]]

In [85]:
get_recommendation(12)

[[2.2385635231727, 203],
 [2.0650680193682267, 2],
 [1.4705095688263776, 93],
 [1.4470025363154255, 95],
 [1.3299285220198291, 200],
 [1.1778533548535854, 75]]

In [86]:
get_recommendation(13)

[[1.1899944637374806, 176]]

In [87]:
get_recommendation(14)

[[2.1501030044105245, 42],
 [1.7243491365603436, 179],
 [1.6782944128748603, 93],
 [1.4828072504044132, 130],
 [1.4364414395730505, 177],
 [1.3770514469008805, 111],
 [1.3672349191864728, 200],
 [1.2710398606329587, 75],
 [1.2354791433351304, 71],
 [0.9100335974117549, 160]]

In [133]:
def get_recommendation_top_cnt(name, top_cnt):
    plants =list(farm.columns)
    score_dic=defaultdict(int) # 평점
    sim_dic=defaultdict(int) # 유사도

    for name2, sim_score in sorted(dict(sim[2]).items(), key = lambda x :x[1], reverse=True)[1:top_cnt + 1]:
        if sim_score > 0 and name != name2: # 박현정과 유사도가 0 이상인 사람에 대해서
            for plant in plants: # 모든 식물을 조사해본다.
                score = 0
                if not farm.loc[name][plant]: # 만약 박현정이 그 식물을 키우지 않는다면,
                    score += farm.loc[name2][plant] * sim_score # 평점 예측 
                    score_dic[plant] += score
                    sim_dic[plant] += sim_score
    
    #print(score_dic)
    #print(sim_dic)
    ret = []
    for key in score_dic.keys():
        score_dic[key] = score_dic[key]/sim_dic[key]
        ret.append([score_dic[key], key])
    
    return sorted(ret, key = lambda x:x[0], reverse = True)

In [137]:
get_recommendation_top_cnt(14, 5)

[[2.374861954721148, 75],
 [2.353602981778023, 130],
 [2.3446990612921037, 179],
 [1.828064605190502, 111],
 [1.6197542794036444, 177],
 [1.6100911098840418, 42],
 [1.429251794588625, 200],
 [1.009249033683048, 71],
 [0.8430425179458862, 160],
 [0.8098426283821093, 93]]

In [138]:
get_recommendation_top_cnt(14, 10)

[[2.269780591725401, 75],
 [2.0953291124118985, 179],
 [1.9021224067216183, 177],
 [1.887468641739338, 130],
 [1.8576832716123124, 42],
 [1.7031019790546726, 111],
 [1.2839166965316766, 93],
 [1.1508780312985305, 200],
 [1.0730299048301675, 71],
 [1.0428463345677534, 160]]

In [136]:
get_recommendation(14)

[[2.1501030044105245, 42],
 [1.7243491365603436, 179],
 [1.6782944128748603, 93],
 [1.4828072504044132, 130],
 [1.4364414395730505, 177],
 [1.3770514469008805, 111],
 [1.3672349191864728, 200],
 [1.2710398606329587, 75],
 [1.2354791433351304, 71],
 [0.9100335974117549, 160]]